# yaml-language-server: $schema=../patch_yaml_model.json
if:
  name: conda-standalone
  timestamp_lt: 1718384287224  # 2024-06-14
  version_eq: "23.5.0"
  subdir_eq: osx-64
  build_number_eq: 0
then:
  - add_constrains: __osx >=10.13
